import type { Metadata } from "next";

import { PropsWithChildren } from "react";
import { getServerAuthSession } from "@/server/auth";
import { redirect } from "next/navigation";
import { unstable_noStore as noStore } from "next/cache";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface AppLayoutProps extends PropsWithChildren {}
export default async function AppLayout({ children }: AppLayoutProps) {
  noStore();
  const session = await getServerAuthSession();
  if (!session) {
    redirect("/auth/login");
  }
  return (
    <main className="flex">
      <div>{children}</div>
    </main>
  );
}
